### ISSUE TITLE
unable to Install node-glfw: No package 'glfw3' found

### ISSUE THREAD

**Issue by RealFreeBrain** [mikeseven/node-glfw#18]
I am getting following error when trying to install node-glfw in my centos 6 machine.
I have already set PKG_CONFIG_PATH to /usr/local/lib/pkgconfig/glfw3.pc

Following is the error:
>npm http GET https://registry.npmjs.org/node-glfw
>npm http 304 https://registry.npmjs.org/node-glfw
>npm WARN engine node-glfw@0.3.1: wanted: {"node":"0.6.5-0.11.10"} (current: >{"node":"v0.10.33","npm":"1.3.6"})
>npm http GET https://registry.npmjs.org/nan
>npm http 304 https://registry.npmjs.org/nan

> node-glfw@0.3.1 install /home/ingole/node_modules/node-glfw
> node-gyp rebuild

Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
Traceback (most recent call last):
  File "/usr/bin/gyp", line 18, in <module>
    sys.exit(gyp.main(sys.argv[1:]))
  File "/usr/lib/python2.6/site-packages/gyp/__init__.py", line 462, in main
    options.circular_check)
  File "/usr/lib/python2.6/site-packages/gyp/__init__.py", line 100, in Load
    depth, generator_input_info, check, circular_check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 2255, in Load
    depth, check)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 388, in LoadTargetBuildFile
    build_file_path)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 1011, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 1026, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, is_late, variables, build_file)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 985, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, is_late, variables, build_file)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 862, in ProcessConditionsInDict
    variables, build_file)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 1011, in ProcessVariablesAndConditionsInDict
    build_file)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 1030, in ProcessVariablesAndConditionsInList
    expanded = ExpandVariables(item, is_late, variables, build_file)
  File "/usr/lib/python2.6/site-packages/gyp/input.py", line 697, in ExpandVariables
    (contents, p.returncode))
Exception: Call to 'pkg-config --libs glfw3 glew' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:428:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ingole/node_modules/node-glfw
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by mikeseven** [comment]
Did u check if pkg-config --cflags glfw works correctly?

-- mike

**Comment by scottstensland** [comment]
I'm getting same error ... 

sudo apt-get install libglfw3-dev

so I do have 

/usr/lib/x86_64-linux-gnu/pkgconfig/glfw3.pc

pkg-config --cflags glfw

fails yet glfw3 is found 

pkg-config --cflags glfw3
-I/usr/include/libdrm 

and

echo $PKG_CONFIG_PATH
/usr/lib/x86_64-linux-gnu/pkgconfig

**Comment by mikeseven** [comment]
hummm once I find some time, I’ll check the project. It’s possible new versions of glfw screwed up the link (not the first time).

— mike

**Comment by RealFreeBrain** [comment]
PKG_CONFIG_PATH should be like this:
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/

and NOT 
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/glfw3.pc

After this,
npm install node-glfw
is working for me. 
pkg-config --cflags glfw still fails.

Thanks all for the help.

**Comment by mikeseven** [comment]
I see. Thanks!

-- mike

**Comment by jhludwig** [comment]
a note for all -- if you are installing in a non-standard directory, then node-glfw will pick up the PKG_CONFIG_PATH settings nicely, but the path to header files (pkg-config --cflags) is not picked up, as there is no macro for that in the binding.gyp file.  not quite sure of best solution yet, just fyi

**Comment by fabrizioschiano** [comment]
I think that this must be related to the error I have below 

```
VulkanBaseApp.cpp:31:10: fatal error: GLFW/glfw3.h: No such file or directory
   31 | #include <GLFW/glfw3.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:446: VulkanBaseApp.o] Error 255 
```

I solved it by doing

`sudo apt-get install xorg-dev libxcb1-dev libglfw3 libglfw3-dev ` 

I took inspiration from this file for [this](https://github.com/NVIDIA/cuda-samples/blob/95b7cea7bcc6971ebc9e1052b30fe60a482f18fe/Samples/simpleVulkanMMAP/Build_instructions.txt). I hope it helps someone else.
