### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by HMUDesign** [mikeseven/node-glfw#21]
I got it all working finally =]

Your binding.gyp file seems to be expending the deps folder to be in a different structure than it is currently.

Presently it is
```
include/
  GL/
  GLFW/
  AntTweakBar.h
```

but binding.gyp references
```
/deps/glew/include
/deps/glew/windows/lib
/deps/glfw/include
/deps/glfw/windows/lib-vc2015
/deps/AntTweakBar/include
/deps/AntTweakBar/windows/lib
```

I downloaded all the deps from their respective sites and organized them how the binding.gyp is expecting and it worked great. (the glfw lib dep is named differently in the latest version, which is why the above references use vc2015 as opposed to what your repo says now).

**Comment by harrison-cross-mmd** [comment]
I had the same issue and working now that I made @HMUDesign changes.  Thanks.

**Comment by mikeseven** [comment]
ouups my bad. I hadn't checked these links. Thanks guys!

**Comment by mikeseven** [comment]
I just reverted the commit so the old structure and files are back. I will update to new re-build later, or if you have them already, send a pull request.
