### ISSUE TITLE
../src/atb.cc:294:57: error: ‘class v8::Isolate’ has no member named ‘GetCurrentContext’

### ISSUE THREAD

**Issue by misaka-10032** [mikeseven/node-glfw#26]
`npm install node-glfw` fails.

https://github.com/mikeseven/node-glfw/blob/dbec0b66116e7ead6fd4f271f19369f7eca3f7a3/src/atb.cc#L265

v8 API seems to be updated. My npm version is 1.3.10.

**Comment by mikeseven** [comment]
Thanks I'll have a look asap.

-- mike

________________________________

**Comment by misaka-10032** [comment]
Well, I guess it's not because of API update, but because I was using an outdated `node`. My `node` version is `v0.10.25`, and I go check the v8 [doc](https://v8docs.nodesource.com/node-0.8/d5/dda/classv8_1_1_isolate.html) for that version, the function was not there. However, for a newer version of node, it should be [there](https://v8docs.nodesource.com/io.js-1.8/d5/dda/classv8_1_1_isolate.html#a81c7a1ed7001ae2a65e89107f75fd053)

I'll try to update my `node`. Sorry about bugging you.
